theme: jekyll-theme-minimal
title:        [Reiser]
description:  [Reiser's GitHub Page]
logo: ["https://www.ducala.org/wp-content/uploads/2018/02/happydog-150x150.jpg"]
show_downloads: ["false"]
google_analytics: [Your Google Analytics tracking ID]
