theme: jekyll-theme-minimal
title:        [Reiser]
description:  [Reiser's GitHub Page]
logo: [https://avatars2.githubusercontent.com/u/19819980?s=460&v=4]
show_downloads: ["false"]
google_analytics: [Your Google Analytics tracking ID]
